---
# use the Ubuntu Trusty Sudo-enabled VM build environment
sudo: required
dist: trusty

language: c

compiler:
    - gcc
    - clang

env:
    global:
        # don't waste travis resources, limit threads count
        - OMP_NUM_THREADS=4
        # set common CMake variables
        - CMAKE_COMMON_VARS="-D CMAKE_VERBOSE_MAKEFILE=ON"

        # coverity related
        - secure: "ZPncDzOLt2e9rb3wCrycqPJHNNtPDjEwJ61dspYbmcLBflHBzoAwTLp3e2UH8p1PufOsf4nNj2SA27Fm47/V0lRZ4TPllwsAzKmWSjVlGWczjpIFT/TMFt6B1rDZ+RLF7J2PQW8t2ZAOJ5wqpHobHijcVtSz4wfiRsGY5Yiavbs0bdGo+CDTl+o8uGqQW5kU66H+C9wBvt2y5WKyp2HnDfojOk7Cp6+Ti5Kcox1AuhwyuQT2iXkmWwKUnTLDuqfHH0kUAnLZMGCAnsg5xnfPKr4/+SZ4QvTnK+Pk8uO6O6Mx3/n3fPyo9i6Gy+Ks7+BGSB173T45CUbWyLd1tu7KSdb2s24lUvK582t4yQ7SJzNnEDg1ENgP9TfjFuLFBEkdlWSVjP4XjrXVujKFzX9hAa2iaquPvFiWvLM6D+a+PVrbuWicRjTpewGFavk0p+Ik+ltFOQMlEcG7P/3iIQZgOF/FQHGYIt3ByOahDUmbyWKQ8DBDc+xPwqlnnDPev/3RIIoAiQPMy/qsJqbCMV8CWmtrMhpSRJdmwtv1n0gpx0DWc7m5Qp/Z1rnmYMmS5Di2oOFm1xfCiLtjX8JLuUlq2rrLrvKiF15CcckpHMmsClv/GztcVNdKCzGx2TcQPDF98SJ0An0bz+Lcao/9OTaBFVtMf2W8edYApAQVzJ82Ex4="
    matrix:
        - MPI=openmpi
        - MPI=mpich

before_install:
    # update, upgrade, and install additional dependencies such as Ubuntu packages
    - sudo apt-get -qq update

install:
    # dependency installation commands
    - extras/install_dependencies_ubuntu.sh

before_script:
    # step out of the source tree and create build directories
    - cd ..
    - mkdir debug_build release_build

script:
    # do a debug out-of-source build
    - cd debug_build
    - cmake $CMAKE_COMMON_VARS -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_BFINDEX=ON ../fdistdump
    - cmake --build .

    - rm -rf *
    - cmake $CMAKE_COMMON_VARS -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_BFINDEX=OFF ../fdistdump
    - cmake --build .
    - cd ..

    # do a release out-of-source build
    - cd release_build
    - cmake $CMAKE_COMMON_VARS -D CMAKE_BUILD_TYPE:STRING=Release -D ENABLE_BFINDEX=ON ../fdistdump
    - cmake --build .

    - rm -rf *
    - cmake $CMAKE_COMMON_VARS -D CMAKE_BUILD_TYPE:STRING=Release -D ENABLE_BFINDEX=OFF ../fdistdump
    - cd ..

# after_success:
    # no tests available yet

# after_failure:

# after_script:

# notifications:
# By default, email notifications are sent to the committer and the commit
# author when they are members of the repository.


# coverity related
addons:
    coverity_scan:
        project:
            name: "CESNET/fdistdump"
            description: "Build submitted via Travis CI"
        notification_email: wrona@cesnet.cz
        build_command_prepend: "./configure; make clean"
        build_command: "make -j 4"
        branch_pattern: coverity_scan
