language: c

before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q openmpi-bin libopenmpi-dev
        - ./install_dependencies.sh
        - export OMPI_CC="${CC}" #CC set by travis as MPI underlying compiler
        - unset CC #unset CC, otherwise ./configure would not set mpicc as CC

install:
        - autoreconf -i
        - ./configure
        - make

#before_script:
#script:
#after_success:
#after_failure:
#after_script:
