#use the Trusty beta build environment
sudo: required
dist: trusty

language: c

compiler:
        - gcc
        #- clang #clang < 3.7 doesn't fully support OpenMP

env:
        global:
                #don't waste travis resources, limit threads
                - OMP_NUM_THREADS=4
                #coverity related
                - secure: "ZPncDzOLt2e9rb3wCrycqPJHNNtPDjEwJ61dspYbmcLBflHBzoAwTLp3e2UH8p1PufOsf4nNj2SA27Fm47/V0lRZ4TPllwsAzKmWSjVlGWczjpIFT/TMFt6B1rDZ+RLF7J2PQW8t2ZAOJ5wqpHobHijcVtSz4wfiRsGY5Yiavbs0bdGo+CDTl+o8uGqQW5kU66H+C9wBvt2y5WKyp2HnDfojOk7Cp6+Ti5Kcox1AuhwyuQT2iXkmWwKUnTLDuqfHH0kUAnLZMGCAnsg5xnfPKr4/+SZ4QvTnK+Pk8uO6O6Mx3/n3fPyo9i6Gy+Ks7+BGSB173T45CUbWyLd1tu7KSdb2s24lUvK582t4yQ7SJzNnEDg1ENgP9TfjFuLFBEkdlWSVjP4XjrXVujKFzX9hAa2iaquPvFiWvLM6D+a+PVrbuWicRjTpewGFavk0p+Ik+ltFOQMlEcG7P/3iIQZgOF/FQHGYIt3ByOahDUmbyWKQ8DBDc+xPwqlnnDPev/3RIIoAiQPMy/qsJqbCMV8CWmtrMhpSRJdmwtv1n0gpx0DWc7m5Qp/Z1rnmYMmS5Di2oOFm1xfCiLtjX8JLuUlq2rrLrvKiF15CcckpHMmsClv/GztcVNdKCzGx2TcQPDF98SJ0An0bz+Lcao/9OTaBFVtMf2W8edYApAQVzJ82Ex4="
        matrix:
                - MPI=openmpi
                - MPI=mpich


before_install:
        #update, upgrade and install common prerequisites
        - sudo apt-get -qq update
        - sudo apt-get -qq upgrade
        - sudo apt-get -qq install gcc automake autoconf libtool
        #install dependencies
        - travis/install_dependencies.sh

        #as long as clang doesn't work, following can by ommited
        #- export OMPI_CC="${CC}" #CC set by travis as OMPI underlying compiler
        #- export MPICH_CC="${CC}"#CC set by travis as MPICH underlying compiler

        - unset CC #otherwise ./configure would not set mpicc as a CC

install:
        - autoreconf -i
        - ./configure --enable-basic-tests
        - make

#before_script:

script:
        - make check
        - make distcheck

#after_success:
after_failure:
        - ./tests/print_logs.sh

#after_script:

notifications:
        email: false

#coverity related
addons:
        coverity_scan:
                project:
                        name: "CESNET/fdistdump"
                        description: "Build submitted via Travis CI"
                notification_email: wrona@cesnet.cz
                build_command_prepend: "./configure; make clean"
                build_command:   "make -j 4"
                branch_pattern: coverity_scan
