language: c

before_install:
        - sudo apt-get update -q
          #default OMPI version (1.4) doesn't comply MPI 2.2, need at least 1.5
        - sudo apt-get install -q openmpi1.5-bin libopenmpi1.5-dev
        - ./install_dependencies.sh
        - export OMPI_CC="${CC}" #CC set by travis as MPI underlying compiler
        - unset CC #unset CC, otherwise ./configure would not set mpicc as CC

install:
        - autoreconf -i
        - ./configure
        - make

#before_script:
#script:
#after_success:
#after_failure:
#after_script:
