language: c

compiler:
        - gcc
        - clang

env:
        - MPI=openmpi
        - MPI=mpich

before_install:
        - sudo apt-get update -q
        - ./travis_install_mpi.sh $MPI
        - ./install_dependencies.sh
        - export OMPI_CC="${CC}" #CC set by travis as MPI underlying compiler
        - unset CC #unset CC, otherwise ./configure would not set mpicc as CC

install:
        - autoreconf -i
        - ./configure
        - make

#before_script:

script:
        - make check

#after_success:
#after_failure:
#after_script:

notifications:
        email: false
