language: c

before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q openmpi-bin libopenmpi-dev
        - ./install_dependencies.sh

install:
        - ./configure
        - make

#before_script:
#script:
#after_success:
#after_failure:
#after_script:
